name: bab3_flutter_layout
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/monumen-kapal-selam-surabaya.jpeg
    - assets/images/monkasel_1.jpg
    - assets/images/monkasel_2.jpeg
    - assets/images/monkasel_3.jpg

  fonts:
    - family: Lobster
      fonts:
      - asset : assets/fonts/Lobster_Regular.ttf

    - family: Oxygen
      fonts:
      - asset : assets/fonts/Oxygen_Regular.ttf
      - asset : assets/fonts/Oxygen_Bold.ttf
        weight: 700

